name: Update Players Data

on:
  schedule:
    - cron: '0 8 * * 2'  # Every Tuesday at 4:00 AM EST (8:00 AM UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_data:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sleeper-api-wrapper

    - name: Fetch Players Data
      run: python data/fetch_players.py
      
    - name: Commit and push if changes
      run: |
        git diff
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add players_data.json
        if git commit -m "Update players data"; then
          git push
        else
          echo "No changes to commit"
        fi
